source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'TestImageGallery' do
	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'SDWebImage', '~> 4.0'
	pod 'KRProgressHUD’
    pod 'SDWebImage/GIF'
    pod 'IQKeyboardManagerSwift'
end
